---
# tasks file for ansible-fleet-cluster
- name: Create systemd drop-in directory
  file: path={{fleet_dropin_dir}} state=directory mode=0755
  sudo: yes

- name: Push ca.crt
  sudo: yes
  copy: src={{local_certs}}/{{etcd_ca_host}}/{{etcd_ca_depot}}/ca.crt dest={{etcd_certs_root}}/
  when: etcd_ca_setup

- name: Uncompress certificates
  sudo: yes
  unarchive: src={{local_certs}}/{{etcd_ca_host}}/{{etcd_ca_depot}}/{{inventory_hostname}}.tar dest={{etcd_certs_root}}
  when: etcd_ca_setup

- name: Set fleet conf
  sudo: yes
  template: src=10-etcd.conf.j2 dest={{fleet_dropin_dir}}/10-etcd.conf
  notify:
    - Reload systemd

- name: Install fleet
  sudo: yes
  shell: systemctl add-wants multi-user.target fleet.service
  register: fleet_install
  changed_when: "'Created symlink' in fleet_install.stdout + fleet_install.stderr"
  notify:
    - Reload systemd

- name: Create env.d dir
  sudo: yes
  file: path=/etc/env.d state=directory mode=0755

- name: Create etcdctl env file
  sudo: yes
  template: src=etcdctl.env.j2 dest=/etc/env.d/etcdctl.env

- name: Create env file
  sudo: yes
  assemble: src=/etc/env.d dest=/etc/environment mode=0644
